trigger:
- master

variables:
  dockerId: vicnys
  imageName: parcel-styled-system

steps:
- script: |
    docker build -t $(dockerId).azurecr.io/$(imageName) .
    echo $(dockerPassword) | docker login -u $(dockerId) --password-stdin $(dockerId).azurecr.io
    docker push $(dockerId).azurecr.io/$(imageName)