#trigger:
#- master

variables:
  dockerId: vicnys
  imageName: parcel-styled-system

steps:
- script: echo "hi there!"
#    docker build -t $(dockerId).azurecr.io/$(imageName) .
#    docker login -u $(dockerId) -p $(pswd) $(dockerId).azurecr.io
#    docker push $(dockerId).azurecr.io/$(imageName)
  env:
    pswd: $(foo)