trigger:
- master

variables:
- group: vnysVars
- name: dockerId
  value: vicnys
- name: imageName
  value: parcel-styled-system  

steps:
- script: |
    docker build -t $(dockerId).azurecr.io/$(imageName) .
    docker login -u $(dockerId) -p $PASSWD $(dockerId).azurecr.io
    docker push $(dockerId).azurecr.io/$(imageName)
  env:
    PASSWD: $(dockerPassword)